uea-machine-learning/tsml

src/main/java/fileIO/OutFile.java

Tony version

---

src/main/java/evaluation/storage/ClassifierResults.java
src/main/java/vector_classifiers/CAWPE.java

el classico == instead of .equals() in classifierresults accuracy computation, also just not computing acc in findallstats() now if it has already been found (or read in) anyway

Fix for bug introduced on friday's hack

---

src/main/java/evaluation/ClassifierResultsAnalysis.java
src/main/java/evaluation/MultipleClassifierEvaluation.java
src/main/java/vector_classifiers/CAWPE.java
src/main/java/vector_classifiers/TunedXGBoost.java

Small fixes to be ported into master while recreating cawpe results and prepping for the stable cawpe paper branch

small fixes/updates found while rereating/updating for cawpe paper

---

.gitignore
.travis.yml
src/main/java/experiments/TransformExperiments.java
src/main/java/experiments/TransformLists.java
src/main/java/timeseriesweka/filters/shapelet_transforms/ShapeletTransform.java

Shapelet fork aaron

---

src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/BayesianOptimisedSearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/ImpRandomSearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/MagnifySearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/RefinedRandomSearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/ShapeletSearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/ShapeletSearchFactory.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/SkewedRandomSearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/SubsampleRandomSearch.java
src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/TabuSearch.java

Refactored use of custom Tuple to use encasulated CandidateSearchData class which contains the parameters. Clearer to read.
Included new WIP: BaysianOpitimised Search Functionality.
@TonyBagnall are you able to attach the issue?

Fixed Issue with parameters in ImpRandomSearch

---

src/main/java/experiments/DataSets.java
src/main/java/experiments/TransformExperiments.java
src/main/java/timeseriesweka/classifiers/BOSS.java
src/main/java/timeseriesweka/classifiers/BagOfPatterns.java
src/main/java/timeseriesweka/classifiers/DD_DTW.java
src/main/java/timeseriesweka/classifiers/ElasticEnsemble.java
src/main/java/timeseriesweka/classifiers/FastShapelets.java
src/main/java/timeseriesweka/classifiers/FlatCote.java
src/main/java/timeseriesweka/classifiers/HiveCote.java
src/main/java/timeseriesweka/classifiers/LPS.java
src/main/java/timeseriesweka/classifiers/NN_CID.java
src/main/java/timeseriesweka/classifiers/RISE.java
src/main/java/timeseriesweka/classifiers/TSBF.java
src/main/java/timeseriesweka/classifiers/TSF.java
src/main/java/timeseriesweka/classifiers/WEASEL.java
src/main/java/timeseriesweka/filters/shapelet_transforms/ShapeletTransform.java

Adding in implements TechnicalInformationHandler to classifiers that have getTechnicalInformation already

Tony branch

---

src/main/java/timeseriesweka/classifiers/WEASEL.java

- apply chi-squared test per window and not on the whole bag-of-patterns

Memory-optimized WEASEL

---

src/main/java/timeseriesweka/filters/shapelet_transforms/ShapeletTransform.java
src/main/java/timeseriesweka/filters/shapelet_transforms/distance_functions/MultivariateDependentDistance.java
src/main/java/timeseriesweka/filters/shapelet_transforms/distance_functions/MultivariateIndependentDistance.java
src/main/java/timeseriesweka/filters/shapelet_transforms/distance_functions/SubSeqDistance.java

allow the use of shapelet matching to remove identical shapelets from different series.

Updated ST

---

src/main/java/evaluation/storage/ClassifierResultsCollection.java
src/main/java/examples/Ex01_Datahandling.java
src/main/java/examples/Ex02_Classifiers.java
src/main/java/examples/Ex03_BasicEvaluation.java
src/main/java/examples/Ex04_BasicExperiments.java
src/main/java/examples/Ex04_ThoroughExperiments.java
src/main/java/examples/Ex05_ThoroughEvaluation.java
src/main/java/experiments/Experiments.java
src/main/java/utilities/InstanceTools.java

A few usage examples/tutorials for all the main stuff in the codebase from a public user standpoint. To be expanded or altered (in terms of their format) over time, but we at least have a place to point to now with some text etc. 
Anyone/everyone feel free to update/add to the examples there, spellcheck etc. I've left the BasicExamples file there in case you'd added to it locally Tony, but it can maybe be deleted
Ex01_DataHandling 
Ex02_Classifiers
Ex03_BasicEvaluation
Ex04_ThoroughExperiments
Ex05_ThoroughEvaluation
Also added a force option to experiments, which I thought I did ages ago but didn't to help with the examples running

Usage examples

---

src/main/java/timeseriesweka/classifiers/dictionary_based/BOSS.java

Update BOSS to output train results files using the current format.

BOSS train results update

---

src/main/java/experiments/ClassifierLists.java
src/main/java/timeseriesweka/classifiers/MultiThreadable.java
src/main/java/timeseriesweka/classifiers/dictionary_based/BOSS.java

Small clean up of BOSS and basic threading interface

Small clean up and basic threading interface

---

src/main/java/experiments/ClassifierLists.java
src/main/java/timeseriesweka/classifiers/dictionary_based/BOSS.java
src/main/java/timeseriesweka/classifiers/dictionary_based/BOSSIndividual.java
src/main/java/timeseriesweka/classifiers/dictionary_based/RBOSS.java
src/main/java/timeseriesweka/classifiers/dictionary_based/boss_variants/BOSSC45.java

Split of RBOSS from BOSS, moved the BOSSIndividual class into its own file.

BOSS Split

---

src/main/java/timeseriesweka/classifiers/dictionary_based/BOSS.java
src/main/java/timeseriesweka/classifiers/dictionary_based/BOSSIndividual.java
src/main/java/timeseriesweka/classifiers/dictionary_based/RBOSS.java
src/main/java/timeseriesweka/clusterers/AbstractTimeSeriesClusterer.java
src/main/java/timeseriesweka/clusterers/AffinityTTS.java
src/main/java/timeseriesweka/clusterers/DictClusterer.java
src/main/java/timeseriesweka/clusterers/KShape.java
src/main/java/timeseriesweka/clusterers/TTC.java
src/main/java/timeseriesweka/clusterers/UnsupervisedShapelets.java
src/main/java/utilities/ClusteringUtilities.java
src/main/java/utilities/Utilities.java
src/main/java/weka_extras/clusterers/AbstractVectorClusterer.java
src/main/java/weka_extras/clusterers/CAST.java
src/main/java/weka_extras/clusterers/DensityPeak.java
src/main/java/weka_extras/clusterers/KMeans.java
src/main/java/weka_extras/clusterers/PAM.java

Don't know when/if i will work on this stuff again, so pushing it to dev. Have cleaned up all of the classes and verified they have close enough accuracy compared to the literature (if applicable). The algorithms currently implemented are:
TSC:
- UnsupervisedShapelets
- KShape
- TTC
Vector:
- k-means
- PAM
- DensityPeaks
- CAST

Clustering algorithms

---

src/main/java/evaluation/storage/ClassifierResults.java
src/main/java/timeseriesweka/classifiers/distance_based/SlowDTW_1NN.java

For some exps I'm running, maybe want it in dev as well if @goastler isn't about to pretty much replace the class? 
Properly populates train classifier results with predictions, and writes the file via cresults method instead of manually
Also changed measurement of build time from millis to nanos, will that break any timing code not using the classifier results times/timeunits?

Slowdtw1nn train file writing updates

---

src/main/java/timeseriesweka/filters/shapelet_transforms/search_functions/BayesianOptimisedSearch.java
src/main/java/utilities/numericalmethods/NelderMead.java
src/main/java/utilities/numericalmethods/NumericalFunction.java

Numerical Minimisation Function.
This is the functionality for minimising an n-dimensional function.
Need to test with data driven functions, rather than just N-d Rosenbrock.

Nelder-Mead Simplex

---

src/main/java/evaluation/storage/ClassifierResults.java
src/main/java/evaluation/storage/ClassifierResultsCollection.java

minor bug in ClassifierResults.java

small bug in loading classifier results

---

src/main/java/timeseriesweka/classifiers/AbstractClassifierWithTrainingInfo.java
src/main/java/timeseriesweka/classifiers/interval_based/LPS.java
src/main/java/timeseriesweka/classifiers/interval_based/TSBF.java
src/main/java/timeseriesweka/classifiers/interval_based/TSF.java
src/main/java/timeseriesweka/classifiers/interval_based/cTSF.java

Fix LPS to allow reproducability

---

src/main/java/timeseriesweka/filters/Spectrogram.java

Added Instance -> spectrogram. This is a bit of an odd usecase as the return type of the process method has to be 2D  which breaks the SimpleBatchFilter abstract class. As a result it does not extend SimpleBatchFilter but does conform to its method naming conventions.

Added Instance to Spectrogram transform.

---

src/main/java/timeseriesweka/filters/Spectrogram.java

Changed Spectrogram such that process() returns relational instance. Also, Spectrogram now extends SimpleBatchFilter.

Updating Spectrogram transform

---

src/main/java/experiments/ClassifierLists.java
src/main/java/timeseriesweka/classifiers/distance_based/elastic_ensemble/Efficient1NN.java
src/main/java/timeseriesweka/classifiers/interval_based/LPS.java
src/main/java/timeseriesweka/classifiers/interval_based/TSBF.java
src/main/java/timeseriesweka/classifiers/shapelet_based/LearnShapelets.java
src/main/java/utilities/ClassifierTools.java

printing now only occurs if debug in EnhanceAbstrClas is true

remove print outs

---

src/main/java/experiments/ClassifierLists.java
src/main/java/experiments/data/DatasetLists.java
src/main/java/timeseriesweka/classifiers/dictionary_based/SpatialBOSS.java
src/main/java/timeseriesweka/classifiers/dictionary_based/WEASEL.java

and bug fix in bespoke classifier list

newProblems27 added to DataSetLists

---

src/main/java/timeseriesweka/classifiers/dictionary_based/SpatialBOSS.java

fixed failing on certain problems (e.g. arrowhead), best distance initialisation was 0, but then certain test cases had literally 0 similarity and so the initial value was never updated)
issue #197

spatialboss

---

src/main/java/experiments/data/DataProcessing.java
src/main/java/experiments/data/DatasetLoading.java

precision changes for arff writing

Dataresampler

---

src/main/java/tsml/classifiers/multivariate/MultivariateAbstractClassifier.java
src/main/java/utilities/multivariate_tools/MultivariateInstanceTools.java

The function splitMultivariateInstanceOnInstances that convert a relational instance to an Instances object was added and to allow verify  missing values

Added check for missing values for multivariate data(relational)

---

src/main/matlab/compResourcesLinePlot.m

Memory evalv2

---

src/main/java/experiments/Experiments.java
src/main/java/machine_learning/classifiers/ensembles/CAWPE.java
src/main/java/machine_learning/classifiers/ensembles/EnsembleSelection.java

a cleanup of experiments, mostly moving sections of setup andrunexperiment, and runexperiment, into their own functions to compartmentalise them

exp cleanup

---

src/main/java/tsml/classifiers/distance_based/distances/twe/TWEDistance.java
src/main/java/tsml/filters/MFCC.java

Following update on https://people.irisa.fr/Pierre-Francois.Marteau/TWED/twed.c

Fix TWE's matrix init Fix package syntax in MFCC

---

src/main/java/experiments/data/TSReader.java

Bug fix for a tsreader error. Univariate dataset printing broken.

Bug fix for TSReader.

---

src/main/java/tsml/classifiers/shapelet_based/ShapeletTransformClassifier.java
src/main/java/tsml/transformers/ConstantAttributeRemover.java
src/main/java/tsml/transformers/PCA.java
src/main/java/tsml/transformers/ShapeletTransform.java
src/main/java/utilities/NumUtils.java

#348 
Implemented/Modified PCA Transformer
Implement ConstantAttributeTransformer
Slight Refactor on NumUtils to move a function out of ST for generic use.

Pca transformer

---

src/main/java/experiments/data/TSReader.java

big speeds up on loading multi/uni problems.

T sreader speedups

---

src/main/java/evaluation/storage/ClassifierResults.java
src/main/java/experiments/data/DatasetLists.java
src/main/java/tsml/classifiers/interval_based/TSF.java

also removed redundant information printed onto line 3

Sort out TSF timing

---

src/main/java/tsml/classifiers/distance_based/distances/wdtw/WDTWDistance.java

PR for https://github.com/uea-machine-learning/tsml/issues/374

fix early abandon WDTW if 2nd series has length=1

---

src/main/java/tsml/classifiers/interval_based/TSF.java
src/main/java/tsml/data_containers/TimeSeries.java
src/main/java/tsml/data_containers/TimeSeriesInstance.java
src/main/java/tsml/data_containers/TimeSeriesInstances.java
src/main/java/tsml/transformers/DimensionIndependentTransformer.java
src/main/java/tsml/transformers/TrainableTransformer.java
src/main/java/tsml/transformers/Transformer.java

some tidying up of transformers, and the skeleton for the new data structure

Data structures dev

---

src/main/java/experiments/ClassifierLists.java

Really tiny change here, noticed NN_ED_D was missing from the allMultivariate list.
Perhaps there's some reason for this I'm not aware of?

Added NN_ED_D to allMultivariate classifiers list.

---

src/main/java/machine_learning/clusterers/AbstractVectorClusterer.java
src/main/java/machine_learning/clusterers/CAST.java
src/main/java/machine_learning/clusterers/DensityPeaks.java
src/main/java/machine_learning/clusterers/KMeans.java
src/main/java/machine_learning/clusterers/PAM.java
src/main/java/tsml/clusterers/AbstractTimeSeriesClusterer.java
src/main/java/tsml/clusterers/DictClusterer.java
src/main/java/tsml/clusterers/KShape.java
src/main/java/tsml/clusterers/TTC.java
src/main/java/tsml/clusterers/UnsupervisedShapelets.java
src/main/java/utilities/ClusteringUtilities.java

Testing the clusterers still work and updating with some old stuff from my branch.

Clusterer Testing

---

src/main/java/tsml/data_containers/TSCapabilities.java
src/main/java/tsml/data_containers/TSCapabilitiesHandler.java
src/main/java/tsml/data_containers/TimeSeriesInstance.java
src/main/java/tsml/data_containers/TimeSeriesInstances.java
src/main/java/tsml/data_containers/ts_fileIO/TSReader.java
src/main/java/tsml/data_containers/utilities/TimeSeriesSummaryStatistics.java
src/main/java/tsml/examples/ts_examples/CapabilitiesExample.java
src/main/java/tsml/transformers/ACF.java
src/main/java/tsml/transformers/CachedTransformer.java
src/main/java/tsml/transformers/DimensionIndependentTransformer.java
src/main/java/tsml/transformers/PACF.java
src/main/java/tsml/transformers/RankOrder.java
src/main/java/tsml/transformers/Transformer.java

TS Capabilities.
This contains extendable functionality for TSClassifiers using TSInstances to express the capabilities they can handle.
This can be extended to allow for the description of mtuli-level capabilities for ensembling purposes etc. But is not part of the current feature set. Need to decide on appropriate syntax for expressing multiple levels of capabilities, or if this should be at the classifier level etc. 
Current Capabilities testing.
EqualLength/Not
Multivariate/Univariate
Missing/Not
MinLength
Capabilities also supports mutual exclusion as well as AND / OR syntax to denote complex capabilities
See new example class on usage. examples/ts_examples/CapabilitiesExamples.java

Ts capabilities

---

src/main/java/evaluation/MultipleClassifiersPairwiseTest.java

Following conv in teams, new clique forming code to trial. Test case of dtw from teams used
output is 
```
cliques = [1 1 1 0 0 0 
0 0 0 1 1 1 
]
```
as expected.
If we accept this and port it in, I'd generally caution that all cd dias going into the mv dami paper at least are double checked for correct cliques

Clique forming

---

src/main/java/tsml/transformers/Convolution.java

#434 
This feature implements Convolutions to aid in the development of the ROCKET classifier.
Transformer contains static functions that perform 1D or 2D convolutions as required.

Convolution feature

---

src/main/java/experiments/Experiments.java

Changed some comments to clarify what settings to change to get an experiment running.
Changed some code layout for readability.

Updated Experiments accessibility for beginners

---

src/main/java/tsml/classifiers/interval_based/TSF.java
src/main/java/tsml/examples/ts_examples/FileReadingExample.java

Added support for the new data model to be used to build the TimeSeriesForest classifier. 
Also created an example to show how to read in both .ts and .arff files to build a classifier using the new data model.

Added support for TSInstances in TSF

---

build.gradle

purge of Deeplearning4j, massive file sizes.

purged DL4j and datavec

---

src/main/java/tsml/data_containers/TimeSeries.java
src/main/java/tsml/transformers/BagOfPatterns.java
src/main/java/tsml/transformers/shapelet_tools/distance_functions/MultivariateDistance.java
src/main/java/tsml/transformers/shapelet_tools/distance_functions/ShapeletDistance.java

#417 
Added JavaDoc comments for all functions in TimeSeries.java.
Also removed getSlidingWindow(start, end) functions as they were doing the same thing as getVSlice(start, end).

TimeSeries JavaDoc + remove duplicate functions

---

src/main/java/evaluation/ClassifierResultsAnalysis.java

Difficult to properly test without setting out/copying the full exps, will let the user (aka you Tony) tests it. Should be fine in theory

estimate timings hacked in

---

src/main/java/evaluation/ClassifierResultsAnalysis.java
src/main/java/evaluation/PerformanceMetric.java
src/main/java/tsml/classifiers/hybrids/Arsenal.java

Estimates now being actually written to file, was just failing and hiding it previously

Estimate writing

---

src/main/java/tsml/data_containers/utilities/Converter.java
src/main/java/tsml/transformers/Resizer.java

This is a small change that fixes converter on a specific case, and adds the resizer.

updated resizer and converter with bug fix.

---

src/main/java/evaluation/ClassifierResultsAnalysis.java

Timings dia hotfix

---

.github/workflows/build-and-test.yml
.github/workflows/gradle-build-and-test.yml
build.gradle

pulling George's github actions branch into master, looks to be working by itself, will just edit this after
on:
push:
branches:
- master
pull_request:
branches:
- master

GitHub actions

---

README.rst

Initial commit to become familiar with the code base. I have filled the table in from the other models in the file tree.

README.rst Update

---

src/main/java/tsml/data_containers/ts_fileIO/TSReader.java

This is the draft PR for the new and improved TS Reader that uses scanner. 
Needs testing thoroughly. but works on both the univariate and multivariate datasets.
Next up is checking the weird special character cases and scientific types.

ts reader now uses scanner

---

src/main/java/tsml/classifiers/interval_based/STSF.java

Added methods to allow for different handling of uneven length series. Algorithm can now handle the input of TimeSeriesInstances data.

Added TimeSeriesInstances capabilities to the STSF algorithm.
